module.exports = {
  requiredIcons: {
    'Icon-36x36.png': { size: 36 },
    'Icon-40x40.png': { size: 40 },
    'Icon-48x48.png': { size: 48 },
    'Icon-58x58.png': { size: 58 },
    'Icon-60x60.png': { size: 60 },
    'Icon-72x72.png': { size: 72 },
    'Icon-80x80.png': { size: 80 },
    'Icon-87x87.png': { size: 87 },
    'Icon-96x96.png': { size: 96 },
    'Icon-120x120.png': { size: 120 },
    'Icon-144x144.png': { size: 144 },
    'Icon-180x180.png': { size: 180 },
    'Icon-192x192.png': { size: 192 },
    'Icon-512x512.png': { size: 512 },
    'Icon-1024x1024.png': { size: 1024 },
  },
  iconContentType: 'image/png',
  moduleLimit: 5,
  version: '1.0',
  checklist: {
    brandingMarketing: {
      url: '/account/app/marketing',
      title: 'Add Your Branding & Marketing',
      description: 'For your app to be listed on the store, we require you provide the branding & marketing details you want used in your app store listing.',
      resolution: 'Update your branding and marketing in "App"<br />(Click To Learn More)',
    },
    payout: {
      url: '/account/settings',
      title: 'Setup Your Payout Settings',
      description: "Before you can earn money from the minimal ads in your app, you're required to setup where we'll send the money you earn.",
      resolution: 'To get paid, add your PayPal in "Account Settings"<br />(Click To Continue)',
    },
    releaseAgreement: {
      url: '/account/legal',
      title: 'E-Sign The Release Agreement',
      description: 'To release your app, Fanapptic is legally required to have signed permission to launch an app with your content on your behalf.',
      resolution: 'Manage your agreements in "Legal Documents"<br />(Click To Continue)',
    },
    tabs: {
      url: '/account/app/tabs',
      title: 'Add At Least 2 Tabs',
      description: 'Your app needs to do something useful. We require you add at least 2 tabs to your app for your users to enjoy.',
      resolution: 'Add &amp; edit tabs in "App"<br />(Click To Continue)',
    },
  },
};
