module.exports = {
  categories: [
    'Books',
    'Business',
    'Education',
    'Entertainment',
    'Finance',
    'Food & Drink',
    'Health & Fitness',
    'Lifestyle',
    'Kids',
    'Magazines & Newspapers',
    'Medical',
    'Music',
    'News',
    'Photo & Video',
    'Productivity',
    'Reference',
    'Shopping',
    'Social Networking',
    'Sports',
    'Travel',
    'Utilities',
  ],
};
