module.exports = {
  categories: [
    'Book',
    'Business',
    'Education',
    'Entertainment',
    'Finance',
    'Apps.Food_Drink',
    'Healthcare_Fitness',
    'Lifestyle',
    'Apps.Newsstand',
    'Medical',
    'Music',
    'News',
    'Photography',
    'Productivity',
    'Reference',
    'Apps.Shopping',
    'SocialNetworking',
    'Sports',
    'Travel',
    'Utilities',
  ],
};
