module.exports = [
  {
    isoCode: 'USD',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'EUR',
    symbol: '€',
    unicode: '&#128;',
    position: 'before',
  },
  {
    isoCode: 'CAD',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'GBP',
    symbol: '£',
    unicode: '&#163;',
    position: 'before',
  },
  {
    isoCode: 'AUD',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'ANG',
    symbol: 'ƒ',
    unicode: '&#x0192;',
    position: 'before',
  },
  {
    isoCode: 'AOA',
    symbol: 'AOA',
    unicode: 'AOA',
    position: 'before',
  },
  {
    isoCode: 'ARS',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'BAM',
    symbol: 'KM',
    unicode: 'KM',
    position: 'before',
  },
  {
    isoCode: 'BBD',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'BGL',
    symbol: 'лв',
    unicode: '&#1083;&#1074;',
    position: 'before',
  },
  {
    isoCode: 'BHD',
    symbol: 'BD',
    unicode: 'BD',
    position: 'after',
  },
  {
    isoCode: 'BND',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'BRL',
    symbol: 'R$',
    unicode: 'R&#36;',
    position: 'before',
  },
  {
    isoCode: 'CHF',
    symbol: 'Fr',
    unicode: 'Fr',
    position: 'before',
  },
  {
    isoCode: 'CLF',
    symbol: 'UF',
    unicode: 'UF',
    position: 'after',
  },
  {
    isoCode: 'CLP',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'CNY',
    symbol: '¥',
    unicode: '&#165;',
    position: 'before',
  },
  {
    isoCode: 'COP',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'CRC',
    symbol: '₡',
    unicode: '&#x20A1;',
    position: 'before',
  },
  {
    isoCode: 'CZK',
    symbol: 'Kč',
    unicode: 'K&#269;',
    position: 'after',
  },
  {
    isoCode: 'DKK',
    symbol: 'kr',
    unicode: 'kr',
    position: 'before',
  },
  {
    isoCode: 'EEK',
    symbol: 'KR',
    unicode: 'KR',
    position: 'before',
  },
  {
    isoCode: 'EGP',
    symbol: 'E£',
    unicode: 'E&#163;',
    position: 'before',
  },
  {
    isoCode: 'FJD',
    symbol: 'FJ$',
    unicode: 'FJ&#36;',
    position: 'before',
  },
  {
    isoCode: 'GTQ',
    symbol: 'Q',
    unicode: 'Q',
    position: 'before',
  },
  {
    isoCode: 'HKD',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'HRK',
    symbol: 'kn',
    unicode: 'kn',
    position: 'before',
  },
  {
    isoCode: 'HUF',
    symbol: 'Ft',
    unicode: 'Ft',
    position: 'before',
  },
  {
    isoCode: 'IDR',
    symbol: 'Rp',
    unicode: 'Rp',
    position: 'before',
  },
  {
    isoCode: 'ILS',
    symbol: '₪',
    unicode: '&#x20AA;',
    position: 'before',
  },
  {
    isoCode: 'INR',
    symbol: 'Rs',
    unicode: 'Rs',
    position: 'before',
  },
  {
    isoCode: 'JPY',
    symbol: '¥',
    unicode: '&#165;',
    position: 'before',
  },
  {
    isoCode: 'KES',
    symbol: 'KSh',
    unicode: 'Ksh',
    position: 'before',
  },
  {
    isoCode: 'KRW',
    symbol: '₩',
    unicode: '&#x20A9;',
    position: 'before',
  },
  {
    isoCode: 'KWD',
    symbol: 'KD',
    unicode: 'KD',
    position: 'after',
  },
  {
    isoCode: 'KYD',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'LTL',
    symbol: 'Lt',
    unicode: 'Lt',
    position: 'before',
  },
  {
    isoCode: 'LVL',
    symbol: 'Ls',
    unicode: 'Ls',
    position: 'before',
  },
  {
    isoCode: 'MVR',
    symbol: 'Rf',
    unicode: 'Rf',
    position: 'before',
  },
  {
    isoCode: 'MXN',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'MYR',
    symbol: 'RM',
    unicode: 'RM',
    position: 'before',
  },
  {
    isoCode: 'NGN',
    symbol: '₦',
    unicode: '&#x20A6;',
    position: 'before',
  },
  {
    isoCode: 'NOK',
    symbol: 'kr',
    unicode: 'kr',
    position: 'before',
  },
  {
    isoCode: 'NZD',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'OMR',
    symbol: 'OMR',
    unicode: '&#65020;',
    position: 'after',
  },
  {
    isoCode: 'PEN',
    symbol: 'S/.',
    unicode: 'S/.',
    position: 'before',
  },
  {
    isoCode: 'PHP',
    symbol: '₱',
    unicode: '&#x20B1;',
    position: 'before',
  },
  {
    isoCode: 'PLN',
    symbol: 'zł',
    unicode: 'Z&#322;',
    position: 'before',
  },
  {
    isoCode: 'QAR',
    symbol: 'QAR',
    unicode: '&#65020;',
    position: 'after',
  },
  {
    isoCode: 'RON',
    symbol: 'lei',
    unicode: 'lei',
    position: 'before',
  },
  {
    isoCode: 'RUB',
    symbol: 'руб.',
    unicode: '&#1088;&#1091;&#1073;',
    position: 'after',
  },
  {
    isoCode: 'SAR',
    symbol: 'SAR',
    unicode: '&#65020;',
    position: 'after',
  },
  {
    isoCode: 'SEK',
    symbol: 'kr',
    unicode: 'kr',
    position: 'before',
  },
  {
    isoCode: 'SGD',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'THB',
    symbol: '฿',
    unicode: '&#322;',
    position: 'before',
  },
  {
    isoCode: 'TRY',
    symbol: 'TL',
    unicode: 'TL',
    position: 'before',
  },
  {
    isoCode: 'TTD',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'TWD',
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'UAH',
    symbol: '₴',
    unicode: '&#8372;',
    position: 'before',
  },
  {
    isoCode: 'VEF',
    symbol: 'Bs F',
    unicode: 'Bs.',
    position: 'before',
  },
  {
    isoCode: 'VND',
    symbol: '₫',
    unicode: '&#x20AB;',
    position: 'before',
  },
  {
    isoCode: 'XCD', 
    symbol: '$',
    unicode: '&#36;',
    position: 'before',
  },
  {
    isoCode: 'ZAR',
    symbol: 'R',
    unicode: 'R',
    position: 'before',
  },
];
