module.exports = {
  categories: [
    'Auto & Vehicles',
    'Beauty',
    'Books & Reference',
    'Business',
    'Comics',
    'Communications',
    'Dating',
    'Education',
    'Entertainment',
    'Events',
    'Finance',
    'Food & Drink',
    'Health & Fitness',
    'House & Home',
    'Lifestyle',
    'Medical',
    'Music & Audio',
    'News & Magazines',
    'Parenting',
    'Photography',
    'Productivity',
    'Shopping',
    'Social',
    'Sports',
    'Travel & Local',
  ],
};
